name: ci
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Setup Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: go.mod
    - name: Test
      run: |
        go vet ./...
        go test -race -cover ./...
        export GOCOVERDIR="$RUNNER_TEMP/covdata"
        mkdir -p "$GOCOVERDIR"
        go test -race ./internal/e2e
        go tool covdata percent -i="$GOCOVERDIR"
    - name: GoReleaser
      uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
      with:
        version: latest
        args: release --snapshot --clean --skip ko
      env:
        KO_DOCKER_REPO: "dummy"
